repos:
  - repo: local
    hooks:
      - id: update-submodules
        name: Update Git Submodules and stage changes
        entry: git submodule update --remote && git add .
        language: system
