#!/bin/sh

# Update submodules
git submodule update --remote --merge

# Stage changes in submodules
git add .

# Optionally, you can add a message to indicate submodule updates
echo "Submodules updated and changes staged."

