name: LADDIE Test Suite - compile and cache LADDIE
run-name: ${{ github.actor }} - LADDIE Test Suite - compile and cache LADDIE
on:
  workflow_call:
  workflow_dispatch:

jobs:
  compile_LADDIE:
    runs-on: ubuntu-latest
    steps:
      - name: Install Homebrew                 # Install Homebrew, needed on Ubuntu runners
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo >> /home/runner/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran
          brew install cmake
          brew install ninja

      - name: Set up Fortran compiler          # See: https://github.com/marketplace/actions/setup-fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - name: Verify compiler setup
        run: gfortran --version

      - name: Checkout LADDIE repository
        uses: actions/checkout@v4

      - name: Ensure compile_LADDIE.csh is executable
        run: chmod +x ./compile_LADDIE.csh

      - name: Compile LADDIE
        run: ./compile_LADDIE.csh clean

      - name: Cache LADDIE program            # TijnB: caching is quite slow, and not optimal here since
        uses: actions/cache/save@v3            # we assume the model code will be changed whenever this workflow
        id: LADDIE_program_cache_save         # is run, so we need to recompile the code anyway.
        with:                                  # So: use artifacts instead!
          path: LADDIE_program
          key: LADDIE_program_${{ github.ref_name }}_${{ github.run_id }}
