# The full LADDIE Test Suite

name: LADDIE Test Suite
run-name: ${{ github.actor }} - LADDIE Test Suite
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  # Compile the model and cache the executable
  compile_and_cache_LADDIE:
    uses: ./.github/workflows/LAD_test_suite_compile_and_cache_LADDIE.yml

  # Run the unit tests and analyse the results
  run_unit_tests:
    needs: compile_and_cache_LADDIE
    uses: ./.github/workflows/LAD_test_suite_run_unit_tests.yml
