name: LADDIE Test Suite - run unit tests
run-name: ${{ github.actor }} - LADDIE Test Suite - run unit tests
on:
  workflow_call:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:

      - name: Restore Homebrew cache
        uses: actions/cache@v4
        with:
          path: |
            /home/linuxbrew/.linuxbrew/Cellar
            /home/linuxbrew/.cache/Homebrew
          key: brew-${{ runner.os }}-${{ hashFiles('**/Brewfile') }}
          restore-keys: |
            brew-${{ runner.os }}-

      - name: Reinstall/initialize Homebrew if needed
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          brew install gcc
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran

      - name: Checkout LADDIE repository
        uses: actions/checkout@v4

      - name: Restore LADDIE program from cache
        uses: actions/cache/restore@v3
        id: LADDIE_program_cache_restore
        with:
          path: LADDIE_program
          key: LADDIE_program_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run unit tests
        run: mpiexec  -n 2  LADDIE_program  unit_tests
